/**
 * Centralized Role-to-Permissions Matrix for Guest Service Requests Management
 */

export type GuestRequestPermission =
  | "GUEST_REQUEST_VIEW"
  | "GUEST_REQUEST_CREATE"
  | "GUEST_REQUEST_UPDATE"
  | "GUEST_REQUEST_ASSIGN"
  | "GUEST_REQUEST_COMPLETE"
  | "GUEST_REQUEST_CANCEL"
  | "GUEST_REQUEST_MANAGE";

export const ROLE_GUEST_REQUEST_PERMISSIONS: Record<
  string,
  GuestRequestPermission[]
> = {
  SUPER_ADMIN: [
    "GUEST_REQUEST_VIEW",
    "GUEST_REQUEST_CREATE",
    "GUEST_REQUEST_UPDATE",
    "GUEST_REQUEST_ASSIGN",
    "GUEST_REQUEST_COMPLETE",
    "GUEST_REQUEST_CANCEL",
    "GUEST_REQUEST_MANAGE",
  ],
  HOTEL_OWNER: [
    "GUEST_REQUEST_VIEW",
    "GUEST_REQUEST_CREATE",
    "GUEST_REQUEST_UPDATE",
    "GUEST_REQUEST_ASSIGN",
    "GUEST_REQUEST_COMPLETE",
    "GUEST_REQUEST_CANCEL",
    "GUEST_REQUEST_MANAGE",
  ],
  GENERAL_MANAGER: [
    "GUEST_REQUEST_VIEW",
    "GUEST_REQUEST_CREATE",
    "GUEST_REQUEST_UPDATE",
    "GUEST_REQUEST_ASSIGN",
    "GUEST_REQUEST_COMPLETE",
    "GUEST_REQUEST_CANCEL",
    "GUEST_REQUEST_MANAGE",
  ],
  FRONT_DESK: [
    "GUEST_REQUEST_VIEW",
    "GUEST_REQUEST_CREATE",
    "GUEST_REQUEST_UPDATE",
    "GUEST_REQUEST_ASSIGN",
    "GUEST_REQUEST_COMPLETE",
    "GUEST_REQUEST_CANCEL",
    "GUEST_REQUEST_MANAGE",
  ],
  RECEPTIONIST: [
    "GUEST_REQUEST_VIEW",
    "GUEST_REQUEST_CREATE",
    "GUEST_REQUEST_UPDATE",
    "GUEST_REQUEST_ASSIGN",
    "GUEST_REQUEST_COMPLETE",
    "GUEST_REQUEST_CANCEL",
  ],
  HOUSEKEEPING: [
    "GUEST_REQUEST_VIEW",
    "GUEST_REQUEST_UPDATE",
    "GUEST_REQUEST_COMPLETE",
  ],
  MAINTENANCE: [
    "GUEST_REQUEST_VIEW",
    "GUEST_REQUEST_UPDATE",
    "GUEST_REQUEST_COMPLETE",
  ],
  RESTAURANT_STAFF: [
    "GUEST_REQUEST_VIEW",
    "GUEST_REQUEST_UPDATE",
    "GUEST_REQUEST_COMPLETE",
  ],
  KITCHEN_STAFF: [
    "GUEST_REQUEST_VIEW",
    "GUEST_REQUEST_UPDATE",
    "GUEST_REQUEST_COMPLETE",
  ],
  ACCOUNTANT: ["GUEST_REQUEST_VIEW"],
};

export function hasGuestRequestPermission(
  role: string | null | undefined,
  permission: GuestRequestPermission
): boolean {
  if (!role) return false;
  const permissions = ROLE_GUEST_REQUEST_PERMISSIONS[role] || [];
  return permissions.includes(permission);
}
